version: '3.8'
services:
  frontend:
    image: 182000022338.dkr.ecr.us-east-1.amazonaws.com/userstory-frontend-repo:latest
    ports:
      - "80:80"  # Публічний доступ до фронтенду
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080/api  # Внутрішня URL для API

  backend:
    image: 182000022338.dkr.ecr.us-east-1.amazonaws.com/userstory-backend-repo:latest
    ports:
      - "8080:8080"  # Публічний доступ до бекенду
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://10.0.2.195:3306/userstory  # IP бази
      - SPRING_DATASOURCE_USERNAME=userstory_admin
      - SPRING_DATASOURCE_PASSWORD=devuser
    depends_on:
      - db  # Для порядку, хоча база зовнішня

  # База даних — зовнішній сервіс, не контейнер
  db:
    image: mariadb:10.11  # Лише для локального тестування, закоментуй на продакшені
    environment:
      - MYSQL_ROOT_PASSWORD=devuser
      - MYSQL_DATABASE=userstory
      - MYSQL_USER=userstory_admin
      - MYSQL_PASSWORD=devuser
    ports:
      - "3306:3306"  # Для локального тестування
    networks:
      - app-network
    # Закоментуй або видали на продакшені, бо база на EC2

networks:
  app-network:
    external: true  # Створена Terraform