version: '3.8'
services:
  frontend:
    image: 182000022338.dkr.ecr.us-east-1.amazonaws.com/userstory-frontend-repo:latest
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      # Використовуємо публічний DNS EC2 для API
      - REACT_APP_API_URL=http://ec2-3-231-93-40.compute-1.amazonaws.com:80/api

  backend:
    image: 182000022338.dkr.ecr.us-east-1.amazonaws.com/userstory-backend-repo:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      # Використовуємо private IP EC2 database instance
      - SPRING_DATASOURCE_URL=jdbc:mariadb://<database_private_ip>:3306/userstory
      - SPRING_DATASOURCE_USERNAME=userstory_admin
      - SPRING_DATASOURCE_PASSWORD=devuser

  # Коментуємо db, бо база працює на EC2
  # db:
  #   image: mariadb:10.11
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=devuser
  #     - MYSQL_DATABASE=userstory
  #     - MYSQL_USER=userstory_admin
  #     - MYSQL_PASSWORD=devuser
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge